version: '3.8'

services:
  shishanavi_database:
    image: postgres:16
    environment:
      POSTGRES_DB: shishanavi_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data-volume:/var/lib/shishanavi_database
    ports:
      - ${POSTGRES_PORT-5432}:5432

volumes:
  data-volume:
    name: shishanavi_database_data_volume
